# Generated by Django 6.0.5 on 2026-05-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Car Name')),
                ('price', models.PositiveIntegerField(verbose_name='Car Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_category', to='main.category')),
            ],
        ),
    ]
